SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[afgprd__Backup230330]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[afgprd__Backup230330](
	[prd__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[prd__rpn] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[uitgeput] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[dat_krea] [date] NOT NULL,
	[dat_afsl] [date] NOT NULL,
	[uur_afsl] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[wie_afsl] [nvarchar](30) COLLATE Latin1_General_CI_AS NOT NULL,
	[kom_afsl] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[omschr__] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[omschr_2] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[prkl_ref] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[typ__dvl] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[mgr__ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[lbl__srt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[magr_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[overlap_] [float] NOT NULL,
	[sealtype_b] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[seal_b] [float] NOT NULL,
	[sealtype_onder] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[seal_h_onder] [float] NOT NULL,
	[gussettype_b] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[rev_prnt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[dos__ref] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[opl__typ] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[opl__oms] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[opltaal1] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[opltaal2] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[opltaal3] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[opltaal4] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[opltaal5] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[opltaal6] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[opltaal7] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[opltaal8] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[opltaal9] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[supp_ant] [int] NOT NULL,
	[ktr__vrs] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[kla__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[ktrk_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[refbykla] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[specif__] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[kpn__srt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[afw__srt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[plano_br] [float] NOT NULL,
	[plano_ln] [float] NOT NULL,
	[afgew_b1] [float] NOT NULL,
	[afgew_ln] [float] NOT NULL,
	[afgew_b2] [float] NOT NULL,
	[vouw___2] [float] NOT NULL,
	[rug_____] [float] NOT NULL,
	[multidrk] [int] NOT NULL,
	[fiat_prd] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[fiat_ant] [int] NOT NULL,
	[fiat____] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[type_ord] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[vpak_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[vpakspec] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[vls__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[bom___ok] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[fmt_eref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[cde___ap] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[prys_srt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[btw_____] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[omzet_wy] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[arek_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[fak___wy] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[wp___ref] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[ksrt_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[dvl__gui] [int] NOT NULL,
	[omsaant_] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[omsaant2] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[omsaant3] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[omsaant4] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[omsaant5] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[omsaant6] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[omsaant7] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[omsaant8] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[omsaant9] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[dgbk_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[oplagtxt] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[oplagtx2] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[oplagtx3] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[oplagtx4] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[oplagtx5] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[oplagtx6] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[oplagtx7] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[oplagtx8] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[oplagtx9] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[extratxt] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[extratx2] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[extratx3] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[extratx4] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[extratx5] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[extratx6] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[extratx7] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[extratx8] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[extratx9] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[intr_ref] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[fpl__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[fplm_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[fpll_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[plwy_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[plwy1ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[plwy2ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[pmd__ref] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[pmdohref] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[pmdghref] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[pmdporef] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[vdt__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[ordsch_2] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[ordsch_3] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[ordsch_4] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[ordsch_5] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[ordsch_6] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[ordsch_7] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrskpsub] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[omd__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[pmd1_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[pmd2_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[omd_vref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[pmd1vref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[pmd2vref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[tmd__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[lmd__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[laybonnr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bon_zelf] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[laybe1nr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bon_ext1] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[laybe2nr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bon_ext2] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[laypbynr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[layrbynr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[laylbynr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bij_drvl] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[laybijnr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bij__and] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvbynr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bij__vrs] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvb1nr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bij_vrs1] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvb2nr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bij_vrs2] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvppnr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvprnr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvpenr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bij__vr2] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvppn2] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvprn2] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvpen2] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bij__vr3] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvppn3] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvprn3] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[layvpen3] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bij__vr4] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[laygroep] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bijgroep] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6pb1] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6pb1] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6pb2] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6pb2] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6pb3] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6pb3] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6pb4] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6pb4] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6pb5] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6pb5] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6pb6] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6pb6] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6pb7] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6pb7] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6pb8] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6pb8] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6vo1] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6vo1] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6vo2] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6vo2] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6vo3] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6vo3] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6bpr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6b_e] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[layv6b2e] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[bonv6bij] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[laycheck] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[boncheck] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_01] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_02] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_03] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_04] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_05] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_06] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_07] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_08] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_09] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_10] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_11] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_12] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_13] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_14] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_15] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[w_oms_16] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_01] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_02] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_03] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_04] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_05] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_06] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_07] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_08] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_09] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_10] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_11] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_12] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_13] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_14] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_15] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_oms_16] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_01] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_02] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_03] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_04] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_05] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_06] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_07] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_08] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_09] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_10] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_11] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_12] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_13] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_14] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_15] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[a_oms_16] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_01] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_02] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_03] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_04] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_05] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_06] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_07] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_08] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_09] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_10] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_11] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_12] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_13] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_14] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_15] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[v_oms_16] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[vwm__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[papplsrt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[paprosrt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[papplref] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[paproref] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[custsize] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[mnpag__x] [float] NOT NULL,
	[mnpag__y] [float] NOT NULL,
	[mxpag__x] [float] NOT NULL,
	[mxpag__y] [float] NOT NULL,
	[etas1ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[etas2ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[etas3ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[etas4ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[etas5ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[off2_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[internet] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[rfqonw4l] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[taal___1] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[taal___2] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[taal___3] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[taal___4] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[taal___5] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[taal___6] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[taal___7] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[taal___8] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[taal___9] [nvarchar](65) COLLATE Latin1_General_CI_AS NOT NULL,
	[min_aant] [int] NOT NULL,
	[max_aant] [int] NOT NULL,
	[cpversie] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[cpautcal] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[cpdirord] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[prodcrea] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[prod_jdf] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[grp__prd] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[grp__inh] [int] NOT NULL,
	[grp__oms] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[grptaal1] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[grptaal2] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[grptaal3] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[grptaal4] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[grptaal5] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[grptaal6] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[grptaal7] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[grptaal8] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[grptaal9] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[emlrfqfm] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[emlrfqkl] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[emlrfqmt] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[emlrfqaf] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[emlrfqvp] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[emlrfq__] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrscpord] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrssplit] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[dvl__oms] [nvarchar](1024) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrs__oms] [nvarchar](1024) COLLATE Latin1_General_CI_AS NOT NULL,
	[dam__oms] [nvarchar](1024) COLLATE Latin1_General_CI_AS NOT NULL,
	[cal__opl] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[virt_vrs] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[gang_vrs] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[rowid] [int] IDENTITY(1,1) NOT NULL,
	[seal_zijkant] [float] NOT NULL,
	[edge_trim] [float] NOT NULL,
	[gap] [float] NOT NULL,
	[fopp2vel] [float] NOT NULL
) ON [PRIMARY]
END
