SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlSnapShot_EOM_grsbon__]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlSnapShot_EOM_grsbon__](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AsOf] [datetime] NOT NULL,
	[grbonref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[grs__vnr] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[compl___] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[lev__tst] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[fac__tst] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[ord__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[suborder] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[grs__com] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[grs_com2] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[art__ref] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[art_oms2] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[zyn__ref] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[art__srt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[art__typ] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[lev__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[lev__rpn] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[glev_dat] [date] NOT NULL,
	[glev_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[glevodat] [date] NOT NULL,
	[glevouur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[levr_dat] [date] NOT NULL,
	[levr_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[gvrz_dat] [date] NOT NULL,
	[gvrz_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[gvrzodat] [date] NOT NULL,
	[gvrzouur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrz__dat] [date] NOT NULL,
	[vrz__uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[elecbest] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[trn__ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[trnt_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[aniv1ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[aniv2ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[aniv3ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[fiat__ok] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[fiat_dat] [date] NOT NULL,
	[fiat_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[fiat_usr] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[fiat_com] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[fiat_num] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval01] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval02] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval03] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval04] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval05] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[gaant___] [float] NOT NULL,
	[gaant_kg] [float] NOT NULL,
	[laant___] [float] NOT NULL,
	[laant_kg] [float] NOT NULL,
	[faant___] [float] NOT NULL,
	[faant_kg] [float] NOT NULL,
	[pak__oms] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[pak__inh] [float] NOT NULL,
	[munt_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[aant_dec] [int] NOT NULL,
	[koers___] [float] NOT NULL,
	[drg_prys] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[bpri__vm] [float] NOT NULL,
	[bpri__bm] [float] NOT NULL,
	[bpri__om] [float] NOT NULL,
	[bprik_vm] [float] NOT NULL,
	[bprik_bm] [float] NOT NULL,
	[bprik_om] [float] NOT NULL,
	[fpri__vm] [float] NOT NULL,
	[fpri__bm] [float] NOT NULL,
	[fpri__om] [float] NOT NULL,
	[fprik_vm] [float] NOT NULL,
	[fprik_bm] [float] NOT NULL,
	[fprik_om] [float] NOT NULL,
	[totfp_vm] [float] NOT NULL,
	[totfp_bm] [float] NOT NULL,
	[totfp_om] [float] NOT NULL,
	[teofk_bm] [float] NOT NULL,
	[fprto2vm] [float] NOT NULL,
	[fprto2bm] [float] NOT NULL,
	[fprto2om] [float] NOT NULL,
	[totbp_bm] [float] NOT NULL,
	[totbp_vm] [float] NOT NULL,
	[totlp_bm] [float] NOT NULL,
	[totlp_vm] [float] NOT NULL,
	[aktr_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[volgnr__] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[salesgroup_id] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[rowid] [int] NOT NULL,
	[tstval06] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval07] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval08] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval09] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval10] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval11] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval12] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval13] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval14] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval15] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval16] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval17] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval18] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval19] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval20] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
 CONSTRAINT [PK_stlSnapShot_EOM_grsbon__] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[stlSnapShot_EOM_grsbon__]') AND name = N'IX_stlSnapShot_EOM_grsbon__glev_dat')
CREATE NONCLUSTERED INDEX [IX_stlSnapShot_EOM_grsbon__glev_dat] ON [dbo].[stlSnapShot_EOM_grsbon__]
(
	[glev_dat] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_stlSnapShot_EOM_grsbon___AsOf]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[stlSnapShot_EOM_grsbon__] ADD  CONSTRAINT [DF_stlSnapShot_EOM_grsbon___AsOf]  DEFAULT (getdate()) FOR [AsOf]
END

