SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[incentXa]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[incentXa](
	[incentXaID] [int] IDENTITY(1,1) NOT NULL,
	[art__ref] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
 CONSTRAINT [PK_incentXa] PRIMARY KEY CLUSTERED 
(
	[incentXaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_incentXa_art__ref]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[incentXa] ADD  CONSTRAINT [DF_incentXa_art__ref]  DEFAULT ('') FOR [art__ref]
END

