SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlArchive_afgsku___Deletes]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlArchive_afgsku___Deletes](
	[aant__ex] [float] NOT NULL,
	[afg__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[box__ref] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[crea_dat] [date] NOT NULL,
	[crea_ori] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[crea_usr] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[crea_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[dos__ref] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[hlf__pos] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[hlf__ref] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[inhoud_flt01] [float] NOT NULL,
	[inhoud_flt02] [float] NOT NULL,
	[inhoud_flt03] [float] NOT NULL,
	[inhoud_flt04] [float] NOT NULL,
	[inhoud01] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[inhoud02] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[inhoud03] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[inhoud04] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[jobnr_archive] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[jobnr_repack] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[jobnr_uit] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[jobnrlev] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[kom__ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[komm_qrt] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[kommen__] [nvarchar](80) COLLATE Latin1_General_CI_AS NOT NULL,
	[lev__dat] [date] NOT NULL,
	[lev__uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[levr_vnr] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[lyn__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[ord__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[ord2_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[pal__ref] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[printed_lyn__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[rowid] [int] NOT NULL,
	[sku__ref] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[sku_source] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[sku_target] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[smpl__ex] [int] NOT NULL,
	[toestand] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[tst__qrt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval01] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval02] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval03] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval04] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval05] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval06] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval07] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval08] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval09] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval10] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[uit__dat] [date] NOT NULL,
	[uit__usr] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[uit__uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[vak__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[versiref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[volgnr__] [int] NOT NULL,
	[vpk__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[vpksrt__] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrm__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrrd__wn] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrrd_dat] [date] NOT NULL,
	[vrrd_usr] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrrd_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrs__ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[weight] [float] NOT NULL,
	[stlArchive_afgsku__] [datetime] NOT NULL
) ON [PRIMARY]
END
