SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlCC_RootCause]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlCC_RootCause](
	[ID] [int] NOT NULL,
	[RootCause] [nvarchar](21) COLLATE Latin1_General_CI_AS NULL,
 CONSTRAINT [PK_stlCC_RootCause] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
