SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlQP_MaterialAvgCosts]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlQP_MaterialAvgCosts](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ParameterID] [int] NOT NULL,
	[FaceSheetMaterialTypeID] [int] NOT NULL,
	[LinerMaterialTypeID] [int] NOT NULL,
	[MaterialCostPerMSI] [float] NOT NULL,
 CONSTRAINT [PK_stlQP_MaterialAvgCosts] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
