SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlREWSPOOL_SettingsLabels]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlREWSPOOL_SettingsLabels](
	[SettingsLabelID] [int] IDENTITY(1,1) NOT NULL,
	[SettingsLabel] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
 CONSTRAINT [PK_stlREWSPOOL_SRC_SettingsLabels] PRIMARY KEY CLUSTERED 
(
	[SettingsLabelID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
