SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlTBC]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlTBC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[access_token_barcode] [nvarchar](11) COLLATE Latin1_General_CI_AS NOT NULL,
	[access_code] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[ImportFileNameID] [int] NULL,
 CONSTRAINT [PK_stlTBC] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[stlTBC]') AND name = N'idx_stlTBC_ImportFileNameID')
CREATE NONCLUSTERED INDEX [idx_stlTBC_ImportFileNameID] ON [dbo].[stlTBC]
(
	[ImportFileNameID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[stlTBC]') AND name = N'IX_stlTBC_access_token_barcode')
CREATE UNIQUE NONCLUSTERED INDEX [IX_stlTBC_access_token_barcode] ON [dbo].[stlTBC]
(
	[access_token_barcode] ASC
)
INCLUDE([access_code]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_stlTBC_ImportFileNameID]') AND parent_object_id = OBJECT_ID(N'[dbo].[stlTBC]'))
ALTER TABLE [dbo].[stlTBC]  WITH CHECK ADD  CONSTRAINT [FK_stlTBC_ImportFileNameID] FOREIGN KEY([ImportFileNameID])
REFERENCES [dbo].[stlTBC_IDIUploades] ([ID])
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_stlTBC_ImportFileNameID]') AND parent_object_id = OBJECT_ID(N'[dbo].[stlTBC]'))
ALTER TABLE [dbo].[stlTBC] CHECK CONSTRAINT [FK_stlTBC_ImportFileNameID]
