SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlDF_ClaimStatus]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlDF_ClaimStatus](
	[stlDF_ClaimStatusID] [int] IDENTITY(1,1) NOT NULL,
	[claimStatus] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
 CONSTRAINT [PK_stlDF_ClaimStatus] PRIMARY KEY CLUSTERED 
(
	[stlDF_ClaimStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
