SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[incentOp]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[incentOp](
	[incentOpID] [int] IDENTITY(1,1) NOT NULL,
	[MinJobs] [int] NOT NULL,
 CONSTRAINT [PK_incentOp] PRIMARY KEY CLUSTERED 
(
	[incentOpID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_incentOp_MinJobs]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[incentOp] ADD  CONSTRAINT [DF_incentOp_MinJobs]  DEFAULT ((0)) FOR [MinJobs]
END

