SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlSalesReportWarehouse]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlSalesReportWarehouse](
	[InvoiceDate] [date] NULL,
	[InvoiceID] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[SequenceNumber] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[CustomerID] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[Customer] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[BrandID] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[Brand] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[SubstrateKey] [nvarchar](17) COLLATE Latin1_General_CI_AS NULL,
	[ProductKW] [nvarchar](25) COLLATE Latin1_General_CI_AS NULL,
	[Description1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Description2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Sales] [float] NULL,
	[InLogin] [float] NOT NULL,
	[InvoicedQty] [float] NULL,
	[ProductGroupID] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[ProductGroup] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[JobID] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[OrderDate] [date] NULL,
	[lyn__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[OrderSalesRep] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SubstrateKey1] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[SubstrateKey2] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[bon__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[arek_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[arek_oms] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[CustomerSalesRep] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ProductID] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[ProductDescription] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[RollSize] [float] NULL,
	[naam____] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[betk_ref] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[CustomerStreet] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CustomerCity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CustomerState] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CustomerZip] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CustomerCountry] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[DeliveryStreet] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DeliveryCity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DeliveryState] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DeliveryZip] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DeliveryCountry] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[amo__akn] [float] NULL,
	[pr_excl_] [float] NULL,
	[PriceType] [nvarchar](19) COLLATE Latin1_General_CI_AS NULL,
	[RealShipmentDate] [date] NULL,
	[kla__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[kla__rpn] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[TrackingNumber] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[CustomerRequestedDeliveryDate] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[bst__ref] [nvarchar](32) COLLATE Latin1_General_CI_AS NULL,
	[CalculationID] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[SalesOrderCalculationID] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[l_aantal] [float] NULL,
	[fac_eenh] [int] NULL,
	[kom__ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ExpectedShipDate] [date] NULL,
	[b_aantal] [float] NULL,
	[aant__e2] [float] NULL,
	[aant__e3] [float] NULL,
	[aant__e4] [float] NULL,
	[aant__e5] [float] NULL,
	[zynrefkl] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SalesOrderComment] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[CustomersOrderNo] [nvarchar](25) COLLATE Latin1_General_CI_AS NULL,
	[Job_QP_ID] [nvarchar](60) COLLATE Latin1_General_CI_AS NULL,
	[Product_QP_ID] [nvarchar](60) COLLATE Latin1_General_CI_AS NULL,
	[lbn__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[stlSalesReportWarehouse]') AND name = N'IX_stlSalesReportWarehouse_InvoiceDate')
CREATE NONCLUSTERED INDEX [IX_stlSalesReportWarehouse_InvoiceDate] ON [dbo].[stlSalesReportWarehouse]
(
	[InvoiceDate] ASC
)
INCLUDE([InvoiceID],[SequenceNumber],[CustomerID],[Customer],[BrandID],[Brand],[SubstrateKey],[ProductKW],[Description1],[Description2],[Sales],[InLogin],[InvoicedQty],[ProductGroupID],[ProductGroup],[JobID],[OrderDate],[lyn__ref],[OrderSalesRep],[SubstrateKey1],[SubstrateKey2],[bon__ref],[arek_ref],[arek_oms],[CustomerSalesRep],[ProductID],[ProductDescription],[RollSize],[naam____],[betk_ref],[CustomerStreet],[CustomerCity],[CustomerState],[CustomerZip],[CustomerCountry],[DeliveryStreet],[DeliveryCity],[DeliveryState],[DeliveryZip],[DeliveryCountry],[amo__akn],[pr_excl_],[PriceType],[RealShipmentDate],[kla__ref],[kla__rpn],[TrackingNumber],[CustomerRequestedDeliveryDate],[bst__ref],[CalculationID],[SalesOrderCalculationID],[l_aantal],[fac_eenh],[kom__ref],[ExpectedShipDate],[b_aantal],[aant__e2],[aant__e3],[aant__e4],[aant__e5],[zynrefkl],[SalesOrderComment],[CustomersOrderNo],[Job_QP_ID],[Product_QP_ID],[lbn__ref]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
