SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stl_GitHubIssues]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stl_GitHubIssues](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ActiveLockReason] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ApiUrl] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[AssigneeId] [bigint] NULL,
	[AssigneeLogin] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[AssigneesCount] [int] NULL,
	[AssigneesList] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[AuthorAssociation] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[AuthorId] [bigint] NULL,
	[AuthorLogin] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[AuthorSiteAdmin] [bit] NULL,
	[AuthorType] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[BlockedByCount] [int] NULL,
	[BlockingCount] [int] NULL,
	[Body] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[BodyLength] [int] NULL,
	[ClosedAt] [datetime2](7) NULL,
	[ClosedAtParsed] [datetime2](7) NULL,
	[CommentsCount] [int] NULL,
	[CommentsUrl] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[CreatedAt] [datetime2](7) NULL,
	[CreatedAtParsed] [datetime2](7) NULL,
	[DayOfWeekCreated] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ETL_BatchId] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ETL_ExtractedAt] [datetime2](7) NULL,
	[ETL_LoadedAt] [datetime2](7) NULL,
	[ETL_ProjectDataHash] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ETL_SourceFile] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ETL_Version] [int] NULL,
	[EventsCount] [int] NULL,
	[EventsUrl] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[HasCodeBlocks] [bit] NULL,
	[HasImages] [bit] NULL,
	[HasLinks] [bit] NULL,
	[HasTaskList] [bit] NULL,
	[HourOfDayCreated] [int] NULL,
	[HtmlUrl] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[IsPullRequest] [bit] NULL,
	[IssueId] [bigint] NULL,
	[IssueNumber] [int] NULL,
	[LabelsColors] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[LabelsCount] [int] NULL,
	[LabelsDescriptions] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[LabelsList] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Locked] [bit] NULL,
	[MentionsCount] [int] NULL,
	[NodeId] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Actual__hrs_] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Assignees] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Due_Date] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Est_Max__hrs_] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Est_Min__hrs_] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Labels] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Linked_pull_requests] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Milestone] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Parent_issue] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Repository] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Requestor] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Reviewers] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Start_Date] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Status] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Sub_issues_progress] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Project_Title] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ProjectCount] [int] NULL,
	[ProjectDataJson] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ProjectFieldPairs] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ProjectFields] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ProjectTitles] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ReactionsConfused] [int] NULL,
	[ReactionsEyes] [int] NULL,
	[ReactionsHeart] [int] NULL,
	[ReactionsHooray] [int] NULL,
	[ReactionsLaugh] [int] NULL,
	[ReactionsMinus1] [int] NULL,
	[ReactionsPlus1] [int] NULL,
	[ReactionsRocket] [int] NULL,
	[ReactionsTotal] [int] NULL,
	[RepoCreatedAt] [datetime2](7) NULL,
	[RepoDefaultBranch] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[RepoDescription] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[RepoForks] [int] NULL,
	[RepoIsArchived] [bit] NULL,
	[RepoIsPrivate] [bit] NULL,
	[RepoLicense] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[RepoOpenIssues] [int] NULL,
	[RepoPrimaryLanguage] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[RepoPushedAt] [datetime2](7) NULL,
	[Repository] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[RepositoryFullName] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[RepositoryUrl] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[RepoSize] [bigint] NULL,
	[RepoStars] [int] NULL,
	[RepoTopics] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[RepoUpdatedAt] [datetime2](7) NULL,
	[RepoWatchers] [int] NULL,
	[State] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[StateReason] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[SubIssuesCompleted] [int] NULL,
	[SubIssuesTotal] [int] NULL,
	[Title] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[TotalBlockedBy] [int] NULL,
	[TotalBlocking] [int] NULL,
	[UniqueParticipants] [int] NULL,
	[UpdatedAt] [datetime2](7) NULL,
	[UpdatedAtParsed] [datetime2](7) NULL,
	[WordCount] [int] NULL,
	[ETL_LastChangeReason] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
