SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlDF_CaughtWhere]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlDF_CaughtWhere](
	[stlDF_CaughtWhereID] [int] IDENTITY(1,1) NOT NULL,
	[caughtWhere] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
 CONSTRAINT [PK_stlDF_CaughtWhere] PRIMARY KEY CLUSTERED 
(
	[stlDF_CaughtWhereID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
