SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlSnapShot_SO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlSnapShot_SO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AsOf] [datetime] NOT NULL,
	[lyn__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[bstvlgnr] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[afg__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[afg__rpn] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[afg2_ref] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[versiref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[zynrefkl] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[afg_oms1] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[afg_oms2] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[kla__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[kla__rpn] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[knp__ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrt__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[ktrk_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[afr__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[munt_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[aant_dec] [int] NOT NULL,
	[koers___] [float] NOT NULL,
	[kitlynrf] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[soortkit] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[orilynrf] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[root_lyn__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[parent_lyn__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[crea_dat] [date] NOT NULL,
	[crea_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[off1_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[prod_off] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[prod_com] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[korting_] [float] NOT NULL,
	[btw_beh_] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[betk_ref] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[betw_ref] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[lyn__srt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[bst__ref] [nvarchar](32) COLLATE Latin1_General_CI_AS NOT NULL,
	[bst__bon] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[bsbn_kla] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[bsbn_kl2] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[bst__url] [nvarchar](255) COLLATE Latin1_General_CI_AS NOT NULL,
	[bst__dat] [date] NOT NULL,
	[bst__uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[bst__com] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[b_aantal] [float] NOT NULL,
	[beaantal] [float] NOT NULL,
	[prys_srt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[prys_typ] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[prys_tst] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[prys_com] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[pr_excl_] [float] NOT NULL,
	[preexcl_] [float] NOT NULL,
	[preexclv] [float] NOT NULL,
	[pr_incl_] [float] NOT NULL,
	[proexcl_] [float] NOT NULL,
	[proexclv] [float] NOT NULL,
	[pr_exclv] [float] NOT NULL,
	[pr_inclv] [float] NOT NULL,
	[btw__ref] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[bedr__bm] [float] NOT NULL,
	[bedr__vm] [float] NOT NULL,
	[bedro_bm] [float] NOT NULL,
	[bedro_vm] [float] NOT NULL,
	[prysvast] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[fac_eenh] [int] NOT NULL,
	[vpakvast] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[vpak_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[aant__e2] [float] NOT NULL,
	[aant__e3] [float] NOT NULL,
	[aant__e4] [float] NOT NULL,
	[aant__e5] [float] NOT NULL,
	[ord__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrs__ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[akplynrf] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[lvb__ref] [nvarchar](58) COLLATE Latin1_General_CI_AS NOT NULL,
	[lbn__ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[lev__com] [nvarchar](4000) COLLATE Latin1_General_CI_AS NOT NULL,
	[lbn__com] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[levvwref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[leverkod] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[l_aantal] [float] NOT NULL,
	[lant_min] [float] NOT NULL,
	[lant_max] [float] NOT NULL,
	[ltol_min] [float] NOT NULL,
	[ltol_max] [float] NOT NULL,
	[vrz__tst] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[laad_tst] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[annul___] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[lev__tst] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrzv_dat] [date] NOT NULL,
	[vrzv_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[levv_dat] [date] NOT NULL,
	[levv_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[levb_dat] [date] NOT NULL,
	[levb_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrz__dat] [date] NOT NULL,
	[vrz__uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[lev__dat] [date] NOT NULL,
	[lev__uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[levtrcom] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrzvodat] [date] NOT NULL,
	[vrzvouur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[levvodat] [date] NOT NULL,
	[levvouur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[vrzvbdat] [date] NOT NULL,
	[vrzvbuur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[levvbdat] [date] NOT NULL,
	[levvbuur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[trn__srt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[lok__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[knplkref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[trn__ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[trnt_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[trsp_dgn] [int] NOT NULL,
	[trsp_urn] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[trsp_typ] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[trng_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[lev__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[lev__rpn] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[aant_pak] [int] NOT NULL,
	[aant_pal] [float] NOT NULL,
	[b_antpak] [int] NOT NULL,
	[b_antpal] [float] NOT NULL,
	[l_antpak] [int] NOT NULL,
	[l_antpal] [float] NOT NULL,
	[extgew__] [float] NOT NULL,
	[b_netto_] [float] NOT NULL,
	[b_tarra_] [float] NOT NULL,
	[l_tarra_] [float] NOT NULL,
	[kolom_6_] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[kolom_7_] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[kolom_8_] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[kolom_9_] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[kolom_10] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[kolom_11] [int] NOT NULL,
	[koloma11] [float] NOT NULL,
	[koloma12] [float] NOT NULL,
	[kolom_13] [float] NOT NULL,
	[gwstintr] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[fmd__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[fac__tst] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[fac__wyz] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[fac__typ] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[fac__grp] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[fac__com] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[fkla_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[knpfcref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[arek_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[f_aantal] [float] NOT NULL,
	[bedrf_bm] [float] NOT NULL,
	[bedrf_vm] [float] NOT NULL,
	[dgbk_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[dossier_] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[fak__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[dok__dat] [date] NOT NULL,
	[bkj__ref] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[peri_ref] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[wp___ref] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[ksrt_ref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[bst__lay] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[uit__lay] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[lvb__lay] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[lvb___ex] [int] NOT NULL,
	[stafprys] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[p_aantal] [float] NOT NULL,
	[ord__grp] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[crea_ori] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[job__inl] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[jobnredi] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[jobnrvrz] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[fiat____] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[flok_ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[flknpref] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[user____] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[supervis] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[betd__vm] [float] NOT NULL,
	[betdmeth] [nvarchar](64) COLLATE Latin1_General_CI_AS NOT NULL,
	[betd_dat] [date] NOT NULL,
	[betd_uur] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[betd_tid] [nvarchar](128) COLLATE Latin1_General_CI_AS NOT NULL,
	[betdcard] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[betd_kla] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[betd_com] [nvarchar](255) COLLATE Latin1_General_CI_AS NOT NULL,
	[betdf_bm] [float] NOT NULL,
	[betdf_vm] [float] NOT NULL,
	[tstval01] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval02] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval03] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval04] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval05] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval06] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval07] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval08] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval09] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[tstval10] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[webshopid] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[land_productie] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[btw_nr_klant] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[betw_srt] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[crea_usr] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[jobnr_archive] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[last_edit_time] [datetime2](3) NOT NULL,
	[last_edit_usr] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[rowid] [int] NOT NULL,
 CONSTRAINT [PK_stlSnapShot_bstlyn__] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[stlSnapShot_SO]') AND name = N'IX_stlSnapShot_bstlyn__AsOf')
CREATE NONCLUSTERED INDEX [IX_stlSnapShot_bstlyn__AsOf] ON [dbo].[stlSnapShot_SO]
(
	[AsOf] ASC
)
INCLUDE([lyn__ref],[bstvlgnr],[afg__ref],[afg__rpn],[afg2_ref],[zynrefkl],[afg_oms1],[afg_oms2],[kla__ref],[kla__rpn],[vrt__ref],[ktrk_ref],[afr__ref],[munt_ref],[aant_dec],[versiref],[kitlynrf],[soortkit],[orilynrf],[root_lyn__ref],[parent_lyn__ref],[knp__ref],[crea_uur],[off1_ref],[prod_off],[prod_com],[korting_],[koers___],[betk_ref],[betw_ref],[lyn__srt],[bst__ref],[bst__bon],[crea_dat],[bsbn_kl2],[bst__url],[bst__dat],[bst__uur],[bst__com],[btw_beh_],[beaantal],[prys_srt],[prys_typ],[prys_tst],[prys_com],[bsbn_kla],[preexcl_],[preexclv],[pr_incl_],[proexcl_],[proexclv],[b_aantal],[pr_inclv],[btw__ref],[bedr__bm],[bedr__vm],[bedro_bm],[pr_excl_],[prysvast],[fac_eenh],[vpakvast],[vpak_ref],[aant__e2],[pr_exclv],[aant__e4],[aant__e5],[ord__ref],[vrs__ref],[akplynrf],[bedro_vm],[lbn__ref],[lev__com],[lbn__com],[levvwref],[leverkod],[aant__e3],[lant_min],[lant_max],[ltol_min],[ltol_max],[vrz__tst],[lvb__ref],[annul___],[lev__tst],[vrzv_dat],[vrzv_uur],[levv_dat],[l_aantal],[levb_dat],[levb_uur],[vrz__dat],[vrz__uur],[lev__dat],[laad_tst],[levtrcom],[vrzvodat],[vrzvouur],[levvodat],[levvouur],[levv_uur],[vrzvbuur],[levvbdat],[levvbuur],[trn__srt],[lok__ref],[lev__uur],[trn__ref],[trnt_ref],[trsp_dgn],[trsp_urn],[trsp_typ],[vrzvbdat],[lev__ref],[lev__rpn],[aant_pak],[aant_pal],[b_antpak],[knplkref],[l_antpak],[l_antpal],[extgew__],[b_netto_],[b_tarra_],[trng_ref],[kolom_6_],[kolom_7_],[kolom_8_],[kolom_9_],[kolom_10],[b_antpal],[koloma11],[koloma12],[kolom_13],[gwstintr],[fmd__ref],[l_tarra_],[fac__wyz],[fac__typ],[fac__grp],[fac__com],[fkla_ref],[kolom_11],[arek_ref],[f_aantal],[bedrf_bm],[bedrf_vm],[dgbk_ref],[fac__tst],[fak__ref],[dok__dat],[bkj__ref],[peri_ref],[wp___ref],[knpfcref],[bst__lay],[uit__lay],[lvb__lay],[lvb___ex],[stafprys],[dossier_],[ord__grp],[crea_ori],[job__inl],[jobnredi],[jobnrvrz],[ksrt_ref],[flok_ref],[flknpref],[user____],[supervis],[betd__vm],[p_aantal],[betd_dat],[betd_uur],[betd_tid],[betdcard],[betd_kla],[fiat____],[betdf_bm],[betdf_vm],[tstval01],[tstval02],[tstval03],[betdmeth],[tstval05],[tstval06],[tstval07],[tstval08],[tstval09],[betd_com],[tstval10],[webshopid],[land_productie],[btw_nr_klant],[rowid],[tstval04]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_stlSnapShot_bstlyn___AsOf]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[stlSnapShot_SO] ADD  CONSTRAINT [DF_stlSnapShot_bstlyn___AsOf]  DEFAULT (getdate()) FOR [AsOf]
END

