SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[incente_200830]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[incente_200830](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[wn___ref] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[ord__ref] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[wn_naam_] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[wn_vnaam] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[wp___ref] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[department] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[est__min] [float] NULL,
	[est__min_2] [float] NULL,
	[e_minutes] [float] NULL,
	[t_minutes] [float] NULL,
	[percent_] [float] NULL,
	[paid__yn] [bit] NULL,
	[pay__amt] [money] NULL,
	[pay__amt_2] [money] NULL,
	[paid_amt] [money] NULL,
	[dat_paid] [datetime] NULL,
	[target_met] [bit] NULL,
	[target_met_2] [bit] NULL,
	[pot__amt] [money] NULL,
	[pot__amt_2] [money] NULL,
	[lastUpdate] [datetime] NULL,
	[locked] [bit] NULL,
	[mgrApproved] [bit] NULL,
	[tmstamp] [timestamp] NULL,
	[exception] [tinyint] NULL,
	[empNo] [int] NULL,
	[overrideReason] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[empMakeReadyMin] [float] NULL,
	[empPrintMin] [float] NULL,
	[empTearDownMin] [float] NULL,
	[empGoodFt] [float] NULL,
	[empTotalFt] [float] NULL,
	[jobTotalGoodFt] [float] NULL,
	[jobEstMakeReadyMin] [float] NULL,
	[jobEstPrintMin] [float] NULL,
	[jobEstTearDownMin] [float] NULL,
	[jobActMakeReadyMin] [float] NULL,
	[jobActPrintMin] [float] NULL,
	[jobActTearDownMin] [float] NULL,
	[empMakeReadyPct] [float] NULL,
	[empPrintPct] [float] NULL,
	[empTeardownPct] [float] NULL,
	[adjMakeReadyMin] [float] NULL,
	[adjPrintMin] [float] NULL,
	[adjTearDownMin] [float] NULL,
	[adjTotJobMin] [float] NULL,
	[adjTotEmpJobMin] [float] NULL
) ON [PRIMARY]
END
