SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stlUT_ServiceAddress]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[stlUT_ServiceAddress](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Address] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[BuildingID] [int] NULL,
	[Suite] [nvarchar](2) COLLATE Latin1_General_CI_AS NULL,
	[NW_AccountID] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
 CONSTRAINT [PK_stlUT_ServiceAddress] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
