SELECT TOP (1000) [id]
      ,[sequentialId]
      ,[assetId]
      ,[locationId]
      ,[priority]
      ,[status]
      ,[title]
      ,[description]
      ,[createdAt]
      ,[updatedAt]
      ,[startDate]
      ,[dueDate]
      ,[completedAt]
      ,[estimatedTime]
      ,[recurrenceType]
      ,[recurrenceInterval]
      ,[recurrenceDay]
      ,[procedureId]
      ,[procedureTitle]
      ,[progressOpenCount]
      ,[progressInProgressCount]
      ,[progressOnHoldCount]
      ,[progressDoneCount]
      ,[thumbnailUrl]
      ,[type]
      ,[full_json]
      ,[last_loaded_at]
  FROM [sqlb00].[dbo].[stl_MaintainX_WorkOrders]

  ORDER BY [last_loaded_at] DESC